* COMMENT SDM
see also ~/org/sdm.org

Intended to span from STB output (first queue) to /submit_to_archive2.pl/

* Overview
The "DAta FLow SIMulator" - DAFLSIM ("daffle sim") simulates the flow
of data given a data-flow diagram.

It requires Python 3.4.


* How graph edges related to simulation
Each graph edge represents data flow between two simulated
object. (see "node types") The types of the nodes on either end of an
edge determine how to link two with simpy.   When neither ends of an
edge is a simpy.Resource, something must be done to insure
the two are simulated sequentially.  This is done by creating an
intervening (simpy) resource. The resource might be viewed as
artificial, but it could also be viewed as a common resource that is
so implicit that we often don't think about it -- namely a CPU (or
thread). For instance, the graph connects to Actions with an edge.
The simulation must create two generators (one for each node of the
edge ends) and a resource ("pipe") that connects them. The pipe
insures that only one of the generator runs at a time AND provides a
mechanism for the first to pass data to the second.


* Input Graphviz (dot) file

DES (Discrete Event Simulation) of data-flow. 

Every node must be of one of the following node types:
- s:: Source
- q:: Queue
- a:: Action
- t:: Terminal
- d:: Database

Node attributes are stored in the dotfile (graphviz) nodes in the
"tooltip" property. Format is: "name1='value2' name2='value2' ..."
Possible attributes are:
- action:: [no default] Node that performs external function. Implies type='a'
- delay::  [default=0]   (minutes)
- duration:: [default=0]
- cron:: [default=None] Hack to allow simulating previous system
- host::   [default="NA-host"]
- source:: [no default] Name of data generator. Implies type='s'
- type:: [no default, but value implied if ACTION and SOURCE given]

If an ACTION is given, then "type='a'" is implied.
If an SOURCE is given, then "type='s'" is implied.

